### ISSUE TITLE
无法自定义适配的URL

### ISSUE THREAD

**Issue by TianshuDing** [hnshhslsh/show-rank#11]
VPN访问图书馆的数据库时，URL不再是插件定义的那几个URL，并且插件不能修改URL。

**Comment by hnshhslsh** [comment]
你可以把源码下载下来，修改`manifest.json`、 `script.js` 文件以及`site` 文件夹对应站点文件里的url（若有），然后点击chrome的右上角三点->更多工具->拓展程序，打开右上角开发者模式，然后选择“加载已解压的扩展程序”载入你的修改版本。

**Comment by TianshuDing** [comment]
感谢作者百忙之中查看邮件。我已经自己修改测试成功，感谢您的建议！



祝您身体健康，工作顺利！
***@***.***
 
发件人： S.H. Lee
发送时间： 2021-05-29 21:05
收件人： hnshhslsh/show-rank
抄送： TianshuDing; Author
主题： Re: [hnshhslsh/show-rank] 无法自定义适配的URL (#11)
你可以把源码下载下来，修改manifest.json、 script.js 文件以及site 文件夹对应站点文件里的url（若有），然后点击chrome的右上角三点->更多工具->拓展程序，打开右上角开发者模式，然后选择“加载已解压的扩展程序”载入你的修改版本。
