### ISSUE TITLE
谷歌学术的功能，在Edge成功，但是在谷歌浏览器失败

### ISSUE THREAD

**Issue by Nixiak-nan** [hnshhslsh/show-rank#12]
如题。Edge能正常显示，控制台没有输出。在谷歌浏览器出现错误，输出如下：
![1](https://user-images.githubusercontent.com/70318059/120925032-2b4c8400-c709-11eb-8898-40680467f378.png)

**Comment by hnshhslsh** [comment]
谷歌学术搜索结果上的每一篇文章都需要访问 DBLP 的 api 进行查询，看报错信息是被同源策略阻止了。我用 Chrome 91 访问了同样的网址没有复现，api 返回头的 `Access-Control-Allow-Origin` 字段是允许了谷歌学术页面的访问的。你可以看下你的对应字段是什么，检查下有没有什么浏览器插件或者设置可能会影响到这里（比如修改了请求的Referer来防止追踪？）。
![image](https://user-images.githubusercontent.com/9738445/120929120-64412480-c71a-11eb-9539-36f5792c136b.png)

**Comment by hnshhslsh** [comment]
谷歌学术搜索结果上的每一篇文章都需要访问 DBLP 的 api 进行查询，看报错信息是被同源策略阻止了。我用 Chrome 91 访问了同样的网址没有复现，api 返回头的 Access-Control-Allow-Origin 字段是允许了谷歌学术页面的访问的。你可以看下你的对应字段是什么，检查下有没有什么浏览器插件或者设置可能会影响到这里（比如修改/禁止了请求的Referer来防止追踪？）。
![image](https://user-images.githubusercontent.com/9738445/120929891-7375a180-c71d-11eb-8efe-76b88daecc1e.png)

**Comment by Nixiak-nan** [comment]
谷歌浏览器版本为84，请求头界面如下所示：Referrer Policy 一致，但是响应头都缺少 Access-Control-Allow-Origin 字段。Edge 浏览器中一切正常。我升级Chrome 91后，一切正常。
![2](https://user-images.githubusercontent.com/70318059/120949835-f88da480-c777-11eb-874f-367b3a2d2ebf.png)
