### ISSUE TITLE
在IEEExplore中使用时存在一些问题

### ISSUE THREAD

**Issue by xiaofeng-github** [hnshhslsh/show-rank#2]
作者你好，很感谢能制作这样一个工具，我在IEEExplore中使用时发现，当进行翻页时，页面就不没有CCF分区的图标了，希望能修改此bug.

**Comment by hnshhslsh** [comment]
已修复。源码和下载链接已更新，chrome商店的版本正在审核中。

**Comment by xiaofeng-github** [comment]
嗯嗯，看到了，非常感谢，科研加油！
