### ISSUE TITLE
dblp_提取期刊全称和缩略名的算法似乎出了问题

### ISSUE THREAD

**Issue by DawdleD** [hnshhslsh/show-rank#3]
如图所示，本应视作为缩写的ASIACRYPTO被当作了全称

![屏幕截图 2020-11-04 103536](https://user-images.githubusercontent.com/38070007/98062853-c175ae80-1e89-11eb-89c0-76d1400c2baa.png)

**Comment by hnshhslsh** [comment]
感谢反馈，已经发布1.6版本修复这个问题。
