### ISSUE TITLE
添加了对EI检索的支持

### ISSUE THREAD

**Issue by Ruiyuan-Zhang** [hnshhslsh/show-rank#9]
您好，

我在您所做的工作的基础上添加了对 https://www.engineeringvillage.com/ 网站的支持。

代码放在我的仓库 https://github.com/zju-zry/show-rank 中，不知道您是否愿意让我将相关的代码和您的程序合并

zju-zry

**Comment by hnshhslsh** [comment]
感谢你对本项目的支持，欢迎提交 Pull request 来贡献代码

**Comment by Ruiyuan-Zhang** [comment]
ok👌🏻
